# To run the mysql database setting in your local host
#server:
#  port: 8001
#
#logging:
#  level:
#    root: info
#  file:
#    name: logs/system.log
#
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/comments
#    username: root
#    password: abc123

#<------------------------------------------------------------------------------>

# Aws mysql database setting
server:
  port: 8001

logging:
  level:
    root: info
  file:
    name: logs/system.log

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comments
    username: root
    password: 123456789

## ddl-auto will need to be changed to different mode